config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  root to: 'restaurants#index'
  resources :restaurants

  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :restaurant, presence: true
  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to @restaurant, notice: 'Thank you for adding a new restaurant to our database!'
    else
      render :new
    end
  end

  def show
    @reviews = @restaurant.reviews
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Thanks for updating the info on this restaurant!'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar.html.erb
_navbar.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |form| %>
  <%= form.input :name %>
  <%= form.input :address %>
  <%= form.input :phone_number %>
  <%= form.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= form.submit "Submit", class: 'btn btn-success' %>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

<div class="container">
  <div class="row">
    <div class="col col-xs-6 col-xs-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

<%= link_to 'Back', @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>

<div>
  <%= link_to 'Add a new restaurant', new_restaurant_path %>
</div>

<div class="container">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col col-xs-6 col-xs-offset-3">
        <h2><%= link_to restaurant.name, restaurant %></h2>
        <h3><%= restaurant.address %></h3>
        <h4><%= restaurant.phone_number %></h4>
        <h4><%= restaurant.category %></h4>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Enter information about a new restaurant</p>

<div class="container">
  <div class="row">
    <div class="col col-xs-6 col-xs-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

<%= link_to 'Back to index', restaurants_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<h3><%= @restaurant.address %></h3>
<h4><%= @restaurant.phone_number %></h4>
<h4><%= @restaurant.category %></h4>

<%= link_to 'Index', restaurants_path %>
<%= link_to 'Edit', edit_restaurant_path %>
<%= link_to 'Delete', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>

<h1>Reviews</h1>

<div class="container">
  <div class="row">
    <% @reviews.each do |review| %>
      <div class="col col-xs-6 col-xs-offset-3">
        <h2>Rating: <%= review.rating %></h2>
        <p><%= review.content %></p>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/_review_form.html.erb
<%= simple_form_for [@restaurant, @review] do |form| %>
  <%= form.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
  <%= form.input :content %>
  <%= form.submit "Review", class: 'btn btn-success' %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>

<div class="container">
  <div class="row">
    <div class="col col-xs-6 col-xs-offset-3">
      <%= render 'review_form' %>
    </div>
  </div>
</div>